### ISSUE TITLE
请问这些.ini文件该怎么使用哪？

### ISSUE THREAD

**Issue by LethargyTeddy** [Nep-Timeline/Clash-Rule-Set#1]
作者你好，请问这些.ini文件怎么使用啊？可以写成脚本吗？

**Comment by Nep-Timeline** [comment]
用订阅转换 例如
https://sub.xeton.dev/sub?target=clash&udp=true&url=你的订阅链接&config=https://nep-timeline.github.io/Clash-Rule-Set/Meta_Config.ini

**Comment by LethargyTeddy** [comment]
> 用订阅转换 例如 [https://sub.xeton.dev/sub?target=clash&udp=true&url=你的订阅链接&config=https://nep-timeline.github.io/Clash-Rule-Set/Meta_Config.ini](https://sub.xeton.dev/sub?target=clash&udp=true&url=%E4%BD%A0%E7%9A%84%E8%AE%A2%E9%98%85%E9%93%BE%E6%8E%A5&config=https://nep-timeline.github.io/Clash-Rule-Set/Meta_Config.ini)

这些.ini配置文件要与相应的.yaml文件配对使用吗？
![图片](https://github.com/Nep-Timeline/Clash-Rule-Set/assets/52397629/a24613c6-f77b-49e3-ba95-14a8f1b0281a)

**Comment by Nep-Timeline** [comment]
后缀带_Config的配置文件会自动把你的订阅转换成yaml里的模板
